### ISSUE TITLE
k3Os

### ISSUE THREAD

**Issue by ThaDaVos** [robbertkl/RancherOS-TransIP#1]
Any idea's on how to do the same with k3Os?
https://github.com/rancher/k3os

https://rancher.com/blog/2019/announcing-k3os-kubernetes-operating-system/

**Comment by ThaDaVos** [comment]
https://github.com/rancher/k3os/issues/48

**Comment by robbertkl** [comment]
It seems this has been resolved in the k3os repo. Did you manage to install k3OS on TransIP?

Closing this issue.
